version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: parkinglot-mysql
    environment:
      MYSQL_ROOT_PASSWORD: biki@RANA27
      MYSQL_DATABASE: parkinglot
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: